version: '3.8'

services:
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # Porta SMTP
      - "8025:8025"   # Interface web para visualizar os e-mails
